Core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Accounts/', include('accounts.urls')),
    path("",include("vaccination_store.urls"))
]

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login',views.login_view,name='login_view'),
    path('',views.logout_view,name='logout'),
    path("profile/",views.profile_view,name='profile'),
    path('edit_profile/<int:id>',views.profile_edit,name="profile_edit"),
    path('profiles/',views.profiles_view,name="profiles"),
    path("delete_user/<int:id>",views.delete_user,name='delete_user'),
    path("password/<int:id>",views.change_password,name="change_password")
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.db.models.signals import post_save
from django.dispatch import receiver
from Core.settings import MEDIA_ROOT
from vaccination_store.models import JobPlace
import os 

# Create your models here.

def upload_pics(inctence,pic):
    profile_folder = os.path.join(MEDIA_ROOT , "Porfiles")
    if not os.path.exists(profile_folder):
        os.makedirs(profile_folder)
    
    new_file_name= f"Profiles/{inctence.id}.{pic.split('.')[1]}"
    new_filePath= os.path.join(MEDIA_ROOT , new_file_name)

 
    if os.path.exists(new_filePath):
        os.remove(new_filePath)
    return new_file_name

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    national_number= models.BigIntegerField(blank=True,null=True)
    address= models.CharField(max_length=50, blank=True, null=True)
    phone_number=models.CharField(max_length=15,null=True,blank=True)
    user_photo=models.ImageField(upload_to=upload_pics,null=True,blank=True)
    job_title= models.CharField(max_length=50,blank=True,null=True)
    job_place=models.ForeignKey(JobPlace,on_delete=models.SET_NULL, null=True,blank=True)

    def __str__(self) :
        if self.user.first_name =='' or self.user.first_name == None:
            return self.user.username
        return self.user.first_name + " "+ self.user.last_name
    
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User 
from .models import Profile
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm

class UserForm(UserCreationForm):
    class Meta:
        model= User 
        fields = ("username",'email','first_name','last_name',"password1","password2",)


class EditUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username",'email','first_name','last_name')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'اسم المستخدم'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'البريد الالكتروني'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'الاسم الاول'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'الاسم الاخير'}),
        }
        labels = {
            'username': 'اسم المستخدم',
            'email': 'البريد الالكتروني',
            'first_name': 'الاسم الاول',
            'last_name': 'الاسم الاخير',
        }


class EditProfileForm(forms.ModelForm):
    class Meta:
        model= Profile
        fields = '__all__'
        exclude= ('user',)
        widgets={
            "national_number":forms.NumberInput(attrs={"placeholder":"الرقم الوطني"}),
            "address":forms.TextInput(attrs={"placeholder":"العنوان"}),
            "phone_number":forms.NumberInput(attrs={"placeholder":"رقم الهاتف"}),
            "job_title":forms.TextInput(attrs={"placeholder":"المسمى الوظيفي"})
        }
        labels = {
            'national_number': 'الرقم الوطني',
            'address': 'العنوان',
            'phone_number': 'رقم الهاتف',
            'user_photo': 'الصورة الشخصية',
            'job_title': 'المسمى الوظيفي',
            'job_place': 'مكان العمل',
        }

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth.decorators import user_passes_test
from .models import Profile,JobPlace
from .forms import *

def is_superuser(user):
    return user.is_superuser
def superuser_required(view_func):
    return user_passes_test(lambda u: u.is_superuser)(view_func)


# Create your views here.
def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        print(request.POST)
        if user is None:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({"error": "اسم المستخدم او كلمة المرور غير صحيحة"}, status=400)
        else:
            login(request, user)
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({"success": "تم تسجيل الدخول بنجاح"})
            return redirect('/')


@login_required(login_url="page_not_found")
def logout_view(request):
    logout(request)
    return redirect('/')


@login_required(login_url="page_not_found")
def profile(request, id):
    if id:
        profile=get_object_or_404(Profile,id=id)
        return render(request,'accounts/profile.html',{"profile":profile})   
    profile=get_object_or_404(Profile,user=request.user)
    return render(request,'accounts/profile.html',{"profile":profile})


@login_required(login_url="page_not_found")
@superuser_required
def profile_edit(request,id):
    profile=get_object_or_404(Profile,id=id)
    if request.user.profile.job_place.id == 1 or profile.job_place == request.user.profile.job_place :
        if request.method == 'POST' and "permissions" not in request.POST:
            formProfile = EditProfileForm(request.POST,request.FILES ,instance=profile)
            formUser=EditUserForm(request.POST,instance=profile.user)
            if formProfile.is_valid() and formUser.is_valid():
                formUser.save()
                myprofile = formProfile.save(commit=False)
                myprofile.user = profile.user
                myprofile.save()
                return redirect(reverse("profiles"))
        if "permissions" in request.POST:
                give_permissions(request,profile.user)
        userForm = EditUserForm(instance=profile.user)
        profileForm=EditProfileForm(instance=profile)
        return render(request,"accounts/profile_edit.html",{"userForm":userForm,"profileForm"
        :profileForm,"profile":profile})
    return redirect(reverse("page_not_found"))


def give_permissions(request ,user):
        permission=request.POST['permissions']
        if permission == 'staff':
            user.is_staff=True
            user.is_superuser=False
        elif permission == 'super':
            user.is_superuser=True
            user.is_staff=True
        else :
            user.is_staff=False
            user.is_superuser=False
        user.is_active=True
        user.save()
        return 



@login_required(login_url="page_not_found")
@superuser_required
def delete_user(request,id):
    user_delete=get_object_or_404(User,id=id)
    if request.method == "POST":
        if request.user == user_delete:
            print("The user is the same of it ")
            return JsonResponse({'error':"Error"},status=400)
        else:
            user_delete.delete()
            return JsonResponse({'success':"success"})
    return render(request,"accounts/delete_user.html",{'user':user_delete})


@login_required(login_url="page_not_found")
@superuser_required
def profiles_view(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            give_permissions(request,User.objects.last())
            last_profile = Profile.objects.last()
            job_place = JobPlace.objects.get(id=request.POST["job_place"])
            last_profile.job_place = job_place
            last_profile.save()
            return JsonResponse({'success':"تمت عملية اضامة المستخدم بنجاح"})
        else :
            return JsonResponse({'error':form.error_messages},status=400)
    job_places=None
    if request.user.profile.job_place.id == 1:
        profiles=Profile.objects.all()
        job_places=JobPlace.objects.all()
    else :
        profiles =Profile.objects.filter(job_place=request.user.profile.job_place)
    context = {"profiles":profiles,"job_places":job_places}
    return render(request , 'accounts/profiles.html',context)

@login_required(login_url="page_not_found")
def profile_view(request):
    profile=get_object_or_404(Profile,user=request.user)
    if profile.user.is_superuser :
        perm="مستخدم مع صلاحيات المدير يمكنه الوصول الى جميع الوظائف"
    elif profile.user.is_staff and not profile.user.is_superuser:
        perm="مستخدم مع صلاحيات تعديل و البحث"
    else: 
        perm="مستخدم مع صلاحيات البحث فقط"
    return render(request,"accounts/profile.html",{"profile":profile,"perm":perm})


@login_required(login_url='page_not_found')
def change_password(request,id):
    user=get_object_or_404(User,id=id)
    if request.method == 'POST':
        new_password = request.POST['new_password1']
        user.set_password(new_password)
        user.save()
        response = JsonResponse({'success': "تم عملية تغير كلمة المرور بنجاح"},status=200 ) 
        return response
    return render(request, 'accounts/change-password.html',{'id':id})

templates/accounts/delete_user.html
{% extends 'base.html' %}
{% block title %}حذف مستخدم{% endblock %}
{% block sub_title %}حذف مستخدم{% endblock %}
{% block content %}

<div style="direction: rtl" class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper bg-dark">
    <!-- Content Header (Page header) -->
    <div class="card card-danger bg-dark">
      <div class="card-header">
        <h3 class="card-title">حذف مستخدم</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form method="POST" enctype="multipart/form-data" id="delete_form">
        {% csrf_token %}
        <div class="row">
          <div class="alert mt-2" id="message"></div>
          <p class="p-3">
            هل انت متأكد انك تريد حذف المستخدم {{user.first_name}}
            {{user.last_name}}؟
          </p>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
          <button type="submit" class="btn btn-danger">حذف</button>
          <a href="{% url 'profiles' %}" type="submit" class="btn btn-primary">تراجع</a>
        </div>
      </form>
    </div>
  </div>
  {% endblock %} {% block scripts %}
  <script>
    $(document).ready(function () {
      $("#message").hide();
      $.ajaxSetup({
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
        },
      });
    });
    $("#delete_form").submit(function (event) {
      event.preventDefault();
      $.ajax({
        url: '{% url "delete_user" user.id %}', // Update the URL endpoint
        type: "POST",
        processData: false,
        contentType: false,
        success: function (data) {
          $("#message").removeClass("alert-success alert-danger");
          $("#message")
            .addClass("alert-success")
            .text("تمت علملية بنجاح !")
            .show();
          setTimeout(function (params) {
            window.location = "/accounts/profiles/"
          }, 2000)
        },
        error: function (error) {
          $("#message").removeClass("alert-success alert-danger");
          $("#message")
            .addClass("alert-danger")
            .text("لا يمكنك حذف هذا المستخدم")
            .show();
        },
      });
    });
  </script>

  {% endblock %}
</div>

templates/accounts/pageNotFound.html
{% extends 'base.html' %} {% load static %} 
{% block custom_css %}
<link rel="stylesheet" href="{% static 'home/css/pageNotFound.css' %}" />
{% endblock custom_css %}
 {% block title %} خطأ في الوصول الى الصفحة{% endblock title%}
{% block sub_title %} لا يمكن لهذا المستخدم الوصول الى هذه الصفحة{% endblock %}
{% block content %}
<div style="direction: rtl" class="wrapper bg-dark">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper bg-dark">
    <!-- Content Header (Page header) -->
    <section id="not-found">
      <div id="title">لم يتم العثور على الصفحة &bull; لا يمكنك الوصول الى هذه الصفحة</div>
      <div class="circles bg-dark">
        <p>
          404<br />
          <small>لا يمكنك الوصول الى هذه الصفحة</small>
        </p>
        <a onclick="history.back()" class="btn btn-primary text-white text-lg">رجوع </a>
        {% if user.is_authincated %}
        <a href='{% url "logout" %}' class="btn btn-danger text-white text-lg">تسجيل الخروج</a>
        {% endif %}
        <span class="circle big"></span>
        <span class="circle med"></span>
        <span class="circle small"></span>
      </div>
    </section>
    
    <!-- Main content -->
  </div>
  <!-- /.content-wrapper -->
</div>
<!-- ./wrapper -->
{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %} {% load static %}

{% block title %}
صفحة الملف الشخصي 
{% endblock title %}

{% block sub_title %}
صفحة الملف الشخصي 
{% endblock %}

{% block content %}
<div style="direction: rtl" class="wrapper">
  <div class="content-wrapper bg-dark">
    <div class="content bg-dark">
      <div class="container-fluid bg-dark">
        <hr class="mt-0 mb-4" />
        <div class="row">
          <div class="col-xl-4 ">
            <div class="card mb-4 mb-xl-0 bg-dark">
              <div class="card-header text-bold">صورة الملف الشخصي</div>
              <div class="card-body text-center">
                <img
                  class="img-account-profile rounded-circle mb-3 h-100 w-100"
                  src="{% if profile.user_photo %}{{profile.user_photo.url}}{% else %}{% static 'home/default_imges/user-defualt.png' %}{% endif %}"
                  alt="" />
                <div class="mb-3">
                  <label for="group">صلاحيات المستخدم</label>
                   <div class="text-center">
                    {{perm}}
                   </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8 bg-dark">
            <div class="card mb-3 bg-dark">
              <div class="card-body bg-dark">
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">اسم المستخدم</h6>
                  </div>
                  <div class="col-sm-9 text-bold">
                    {{user.username}}
                  </div>
                </div>
                <hr />
                <div class="row">
                  <div class="col-sm-3 ">
                    <h6 class="mb-0">الاسم بالكامل</h6>
                  </div>
                  <div class="col-sm-9 text-bold ">
                    {{user.first_name}} {{user.last_name}}
                  </div>
                </div>
                <hr />
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">البريد الالكتروني</h6>
                  </div>
                  <div class="col-sm-9  text-bold">{{user.email}}</div>
                </div>
                <hr />
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">رقم الهاتف</h6>
                  </div>
                  <div class="col-sm-9 text-bold">
                    {{profile.phone_number}}
                  </div>
                </div>
                <hr />
                <div class="row">
                  <div class="col-sm-3 ">
                    <h6 class="mb-0">الرقم الوطني</h6>
                  </div>
                  <div class="col-sm-9 text-bold ">
                    {{profile.national_number}}
                  </div>
                </div>
                <hr />
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">العنوان</h6>
                  </div>
                  <div class="col-sm-9 text-bold ">{{profile.address}}</div>
                </div>
                <hr />
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">مكان العمل</h6>
                  </div>
                  <div class="col-sm-9 text-bold ">{{profile.job_place}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/profiles.html
<!-- في المكان ده هحط المحتوى -->
{% extends 'base.html' %} {% load static %} {% block custom_css %}
<link rel="stylesheet" href="{% static 'home/css/profiles.css' %}" />
{% endblock custom_css %} {% block title %}المستخدمين{% endblock %} 
{% block sub_title %}المستخدمين{% endblock %} 
{% block content%}
<div style="direction: rtl" class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper bg-dark">
    <!-- Content Header (Page header) -->
    <!--اظافة موظف-->
    <div class="content bg-dark">
      <div class="container-fluid bg-dark">
        <div class="row">
          <div class="col-12 col-sm-6 col-lg-3 mt-3">
            <a data-bs-toggle="modal" data-bs-target="#addUser">
              <div
                class="single_advisor_profile wow fadeInUp"
                data-wow-delay="0.2s"
                style="
                  visibility: visible;
                  animation-delay: 0.2s;
                  animation-name: fadeInUp;
                ">
                <!-- Team Thumb-->
                <div class="advisor_thumb">
                  <img
                    src=" {% static 'dist/img/addUser.png' %}"
                    style="wdith: 300px; height: 300px"
                    alt="" />
                </div>
                <!-- Team Details-->
                <div class="single_advisor_details_info">
                  <h6>إضافة مستخدم</h6>
                  <p class="designation">انقر هنا لإضافة مستخدم</p>
                </div>
              </div></a
            >
          </div>
          {% for profile in profiles %}
          <!-- Single Advisor-->
          <div class="col-12 col-sm-6 col-lg-3 mt-3">
            <a href="{% url 'profile_edit' profile.id %}"
              ><div
                class="single_advisor_profile wow fadeInUp"
                data-wow-delay="0.2s"
                style="
                  visibility: visible;
                  animation-delay: 0.2s;
                  animation-name: fadeInUp;
                ">
                <!-- Team Thumb-->
                <div class="advisor_thumb">
                  <img
                    src="{% if profile.user_photo %}{{profile.user_photo.url}} {% else %} {% static 'home/default_imges/user-defualt.png' %} {% endif %}"
                    style="wdith: 300px; height: 300px"
                    alt="" />
                </div>
                <!-- Team Details-->
                <div class="single_advisor_details_info">
                  <h6>{{profile}}</h6>
                  <p class="designation">{{profile.job_title}}</p>
                </div>
              </div></a
            >
          </div>
          {% endfor %}
        </div>
        <div
          class="modal fade"
          id="addUser"
          tabindex="-1"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content bg-dark">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                  اضافة مستخدم جديد
                </h5>
                <button
                  type="button"
                  class="btn-close m-0 bg-white"
                  data-bs-dismiss="modal"
                  aria-label="Close"></button>
              </div>
              <div class="modal-body">
                الرجاء ادخال البيانات بشكل صحيح
                <form method="POST" enctype="multipart/form-data" id="UserForm">
                  {% csrf_token %}
                  <div class="alert mb-2" id="Message"></div>
                  <div class="card-body">
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label class="form-label" for="id_username"
                          >اسم المستخدم</label
                        ><input
                          type="text"
                          name="username"
                          maxlength="150"
                          class="form-control"
                          placeholder="الرجاء ادخال اسم المستخدم"
                          required=""
                          id="id_username" />
                      </div>
                      <div class="from-group col-md-6">
                        <label class="form-label" for="id_email"
                          >البريد الالكتروني
                        </label>
                        <input
                          type="email"
                          name="email"
                          maxlength="75"
                          class="form-control"
                          placeholder="الرجاء ادخال البريد الالكتروني لهذا المستخدم" />
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label class="form-label" for="id_first_name"
                          >الاسم الأول</label
                        >
                        <input
                          type="text"
                          name="first_name"
                          maxlength="150"
                          class="form-control"
                          placeholder="رجاء ادخال الاسم الاول"
                          id="id_first_name" />
                      </div>
                      <div class="form-group col-md-6">
                        <label class="form-label" for="id_last_name"
                          >الاسم الاخير</label
                        >
                        <input
                          type="text"
                          name="last_name"
                          maxlength="150"
                          class="form-control"
                          placeholder="الرجاء ادخال الاسم الاخير"
                          id="id_last_name" />
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label class="form-label" for="id_password"
                          >كلمة المرور</label
                        >
                        <input
                          type="password"
                          name="password1"
                          oninput="strengthChecker()"
                          maxlength="128"
                          class="form-control"
                          placeholder="رجاء ادخال كلمة مرور لهذا المستخدم"
                          required=""
                          id="id_password1" />
                        <span id="toggle" onclick="toggle()">
                          <i class="fas fa-eye"></i>
                        </span>
                        <div id="strength-bar"></div>
                      </div>
                      <div class="form-group col-md-6">
                        <label class="form-label" for="id_password"
                          >تأكيد كلمة المرور
                        </label>
                        <input
                          type="password"
                          name="password2"
                          maxlength="128"
                          class="form-control"
                          placeholder="رجاء اعادة ادخال كلمة مرور"
                          required=""
                          oninput="checkMatch()"
                          id="id_password2" />
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label for="group">صلاحيات المستخدم</label>
                        <select
                          class="form-select"
                          id="group"
                          name="permissions"
                          aria-label="مستخدم مع صلاحيات البحث فقط">
                          <option value="user">
                            مستخدم مع صلاحيات البحث فقط
                          </option>
                          <option value="staff">
                            مستخدم مع صلاحيات تعديل و البحث
                          </option>
                          <option value="super">
                            مستخدم مع صلاحيات المدير يمكنه الوصول الى جميع
                            الوظائف
                          </option>
                        </select>
                      </div>
                      <div class="form-group col-md-6">
                          <label class="form-label" for="id_job_place">جهة العمل</label>
                          <select
                            name="job_place"
                            class="form-select"
                            required
                            id="id_job_place"
                            fdprocessedid="jp2iza">
                            {% if job_places  %}
                            {% for job_place  in job_places %}
                            <option value="{{job_place.id}}">
                              {{job_place}}
                            </option>
                            {% endfor %}
                            {% else %}
                              <option value="{{user.profile.job_place.id}}">
                              {{user.profile.job_place}}
                            </option>
                            {% endif %}
                          </select>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button
                      type="submit"
                      id="submitBtn"
                      class="btn btn-success w-25 h-25">
                      اضافة
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block scripts %}
<script>
  $(document).ready(function () {
    $("#Message").hide();
    $.ajaxSetup({
      headers: {
        "X-CSRFToken": "{{ csrf_token }}",
      },
    });
  });
  let parameters = {
    count: false,
    letters: false,
    numbers: false,
    special: false,
  };
  let strengthBar = document.getElementById("strength-bar");

  function strengthChecker() {
    let password = document.getElementById("id_password1").value;

    parameters.letters = /[A-Za-z]+/.test(password) ? true : false;
    parameters.numbers = /[0-9]+/.test(password) ? true : false;
    parameters.special = /[!\"$%&/()=?@~`\\.\';:+=^*_-]+/.test(password)
      ? true
      : false;
    parameters.count = password.length > 7 ? true : false;

    let barLength = Object.values(parameters).filter((value) => value);

    console.log(Object.values(parameters), barLength);

    strengthBar.innerHTML = "";
    for (let i in barLength) {
      let span = document.createElement("span");
      span.classList.add("strength");
      strengthBar.appendChild(span);
    }

    let spanRef = document.getElementsByClassName("strength");
    for (let i = 0; i < spanRef.length; i++) {
      switch (spanRef.length - 1) {
        case 0:
          spanRef[i].style.background = "#ff3e36";
          break;
        case 1:
          spanRef[i].style.background = "#ff691f";
          break;
        case 2:
          spanRef[i].style.background = "#ffda36";
          break;
        case 3:
          spanRef[i].style.background = "#0be881";
          break;
      }
    }
  }
  function toggle() {
    let password = document.getElementById("id_password1");
    let eye = document.getElementById("toggle");

    if (password.getAttribute("type") == "password") {
      password.setAttribute("type", "text");
      eye.style.color = "#062b61";
    } else {
      password.setAttribute("type", "password");
      eye.style.color = "#6b6868";
    }
  }
  $("#UserForm").submit(function (event) {
    event.preventDefault();
    var formData = new FormData(this);
    $.ajax({
      url: '{% url "profiles" %}', // Update the URL endpoint
      type: "POST",
      data: formData,
      processData: false,
      contentType: false,
      success: function (data) {
        $("#Message").removeClass("alert-success alert-danger");
        $("#Message")
          .addClass("alert-success")
          .text("تمت علملية بنجاح !")
          .show();
          setTimeout(() => {
            window.location.href='/';
          },3000)
      },
      error: function (error) {
        $("#Message").removeClass("alert-success alert-danger");
        $("#Message")
          .addClass("alert-danger")
          .text("تأكد من ادخال البيانات بشكل صحيح")
          .show();
      },
    });
  });

  function checkMatch() {
    let password = document.getElementById("id_password1");
    let password2 = document.getElementById("id_password2");
    if (password.value !== password2.value) {
      password2.classList.remove("is-valid");
      password2.classList.add("is-invalid");
    } else {
      password2.classList.remove("is-invalid");
      password2.classList.add("is-valid");
    }
  }
</script>
{% endblock scripts %}