Core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Accounts/', include('accounts.urls')),
    path("",include("vaccination_store.urls"))
]

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

vaccination_store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index_view,name="index_view"),
    path('JobPlaces/',views.job_place,name="job_places"),
    path('Vaccination/',views.vacciantion,name="vaccination"),
]

vaccination_store/models.py
from django.db import models


class Vaccination(models.Model):
    VACCINE_TYPES = [
        ('BCG', 'تطعيم المواليد - بي سي جي'),
        ('Polio_Newborn', 'تطعيم المواليد - شلل الأطفال'),
        ('Hexavalent_2Months', 'تطعيم الشهرين - الطعم السداسي'),
        ('Rotavirus_2Months', 'تطعيم الشهرين - طعم الروتا'),
        ('Hexavalent_4Months', 'تطعيم الأربعة شهور - الطعم السداسي'),
        ('Rotavirus_4Months', 'تطعيم الأربعة شهور - طعم الروتا'),
        ('Hexavalent_6Months', 'تطعيم الستة شهور - الطعم السداسي'),
        ('Rotavirus_6Months', 'تطعيم الستة شهور - طعم الروتا'),
        ('Meningococcal_9Months', 'تطعيم التسعة شهور - تطعيمة التهاب السحايا A.C.Y.W135'),
        ('Polio_9Months', 'تطعيم التسعة شهور - ال'),
        ('Pneumococcal_1Year', 'تطعيم السنة - طعتطعيمة الوقاية من شلل الأطفم الرئوي 13'),
        ('Pentavalent_1.5Years', 'تطعيم السنة والنصف - الطعم الخماسي'),
    ]

    name = models.CharField(max_length=255, verbose_name='اسم التطعيم')
    vaccine_type = models.CharField(max_length=50, choices=VACCINE_TYPES, verbose_name='نوع التطعيم')
    expired_date = models.DateField(verbose_name='تاريخ انتهاء الصلاحية')
    description = models.TextField(verbose_name='وصف التطعيم')
    available_doses = models.IntegerField(verbose_name='عدد الجرعات المتاحة')

    def __str__(self):
        return f"{self.name} - {self.vaccine_type}"



class JobPlace(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=50)
    location = models.URLField()
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return self.name 

    

vaccination_store/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import JobPlace,Vaccination
from .form import JobPlaceForm,VaccinationForm
from django.contrib.auth.decorators import user_passes_test,login_required


def is_superuser(user):
    return user.is_superuser
def superuser_required(view_func):
    return user_passes_test(lambda u: u.is_superuser)(view_func)

# Create your views here.
def index_view(request):
    return render(request,"vaccination_store/index.html")

@login_required
@superuser_required
def vacciantion(request):
    if request.method == "POST":
        form= VaccinationForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({"message":"success"},status=201)
        else :
            return JsonResponse({"error":"there's error"},status=400)
    form = VaccinationForm()
    vaccinations=Vaccination.objects.all()
    context= {"form":form,"vaccinations":vaccinations}
    return render(request, "vaccination_store/vaccination.html",context)

@login_required
@superuser_required
def job_place(request):
    if 'id' in  request.POST:
        id = request.POST['id']
        obj = JobPlace.objects.get(pk=id)
        obj.delete()
        return JsonResponse({"success":"the job deleted successfuly "},status=200)
    if request.method == "POST":
        form = JobPlaceForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({"success":"the job place added successfuly "},status=200)
    job_places = JobPlace.objects.all()
    form = JobPlaceForm()
    return render(request,"vaccination_store/job_place.html",{"job_places":job_places,"form":form})

templates/vaccination_store/index.html
{% extends 'base.html' %} {% load static %} {% block title %}منظومة التطعيمات
للمراكز الصحية قصر بن غشير {% endblock %} {% block content %}
<style>
  .carousel-item {
    position: relative;
  }

  .carousel-item {
    transition: transform 0.5s ease;
    /* Adjust the duration and timing function as needed */
  }
  .carousel-item > img {
    width: 100%;
    height: 25%;
  }

  .carousel-item.active {
    transform: scale(1.1);
    /* Adjust the scale factor as needed */
  }

  .overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.6);
    /* Adjust the last value for the opacity */
  }
</style>
<div style="direction: rtl" class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper bg-dark">
    <!-- Content Header (Page header) -->
    <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button
          type="button"
          data-bs-target="#myCarousel"
          data-bs-slide-to="0"
          class="active"
          aria-label="Slide 1"
          aria-current="true"></button>
        <button
          type="button"
          data-bs-target="#myCarousel"
          data-bs-slide-to="1"
          aria-label="Slide 2"
          class=""></button>
        <button
          type="button"
          data-bs-target="#myCarousel"
          data-bs-slide-to="2"
          aria-label="Slide 3"
          class=""></button>
        <button
          type="button"
          data-bs-target="#myCarousel"
          data-bs-slide-to="3"
          aria-label="Slide 4"
          class=""></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img
            src="{% static 'index_pictures/1.jpg' %}"
            alt=""
            class="d-block w-100 h-25" />
          <div class="overlay"></div>
          <div class="container">
            <div class="carousel-caption text-start">
              <h1>المراكز الصحية</h1>
              <p class="opacity-75">منظومة التطعيمات الاولى في قصر بن غشير</p>
              {% if not user.is_authenticated %}
              <p>
                <a
                  class="btn btn-lg btn-primary"
                  data-bs-toggle="modal"
                  data-bs-target="#loginModal"
                  >تسجيل الدخول</a
                >
              </p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="carousel-item">
          <img
            src="{% static 'index_pictures/2.jpeg' %}"
            alt=""
            class="d-block w-100 h-25" />
          <div class="overlay"></div>
          <div class="container">
            <div class="carousel-caption">
              <h1>تحقق من وجود التطعيمات في اقرب مركز الصحي</h1>
              <p>
                <a class="btn btn-lg btn-primary" href="{% url 'job_places' %}"
                  >تعرف على المزيد</a
                >
              </p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'index_pictures/3.jpg' %}"
            alt=""
            class="d-block" />
          <div class="overlay"></div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'index_pictures/4.jpg' %}"
            alt=""
            class="d-block" />
          <div class="overlay"></div>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock content %} 
  {% block scripts %}
  <script>
    const myCarouselElement = document.getElementById("myCarousel");
    const carousel = new bootstrap.Carousel(myCarouselElement, {
      interval: 3000,
      touch: true,
    });
  </script>
  {% endblock scripts %}

templates/vaccination_store/vaccination.html
{% extends "base.html" %} {% block title %}التطعيمات{% endblock title %}
{% load static %}
{% block content %}

<div style="direction: rtl" class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper bg-dark">
        <!-- Content Header (Page header) -->
        <div class="content bg-dark">
            <div class="container-fluid bg-dark">
                <div class="col-12">
                    <!-- Account details card-->
                    <div class="card card-navy mt-4 bg-dark">
                        <div class="card-header d-flex justify-content-center fs-4">
                            التطعيمات
                        </div>
                        <div class="card-body">
                            <div class="col-12">
                                <div class="my-custom-scrollbar">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="text-center">اسم المطعوم</th>
                                                <th class="text-center"> نوع المطعوم</th>
                                                <th class="text-center">الكمية المتوفرة في المخزن</th>
                                                <th class="text-center">تاريخ الانتهاء</th>
                                                <th class="text-center">شريحة المستهدفة</th>
                                                <th class="text-center d-print-none">الاجراءات</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tbody">
                                            {% for vaccine in vaccinations %}
                                            <tr>
                                                <td class="text-center">{{ vaccine.name }}</td>
                                                <td class="text-center">{{ vaccine.vaccine_type }}</td>
                                                <td class="text-center">{{ vaccine.available_doses }}</td>
                                                <td class="text-center">{{ vaccine.expired_date }}</td>

                                                <td class="text-center">
                                                    {{ vaccine.description }}
                                                </td>
                                                <td class="text-center">
                                                    <div class="dropdown">
                                                        <button class="btn bg-navy dropdown-toggle d-print-none"
                                                            type="button" id="`actionsDropdown${employee.id}`"
                                                            data-bs-toggle="dropdown" aria-haspopup="true"
                                                            aria-expanded="false">
                                                            الإجراءات
                                                        </button>
                                                        <div class="dropdown-menu"
                                                            aria-labelledby="`actionsDropdown${employee.id}`">
                                                            <a class="dropdown-item" href="#">عرض جهة العمل</a>
                                                            <a class="dropdown-item" href="#">تعديل جهة العمل</a>
                                                            <a class="dropdown-item"
                                                                onclick="UpdateEmployeeName(this.parentElement.parentElement.parentElement.parentElement)"
                                                                class="dropdown-item" data-bs-toggle="modal"
                                                                data-bs-target="#message">حذف جهة العمل</a>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-12 mt-5 d-print-none">
                                <button onclick="history.back()" type="button" class="btn btn-danger w-25 h-25">
                                    رجوع <i class="fa fa-undo-alt fa-rotate-180 ml-3"></i>
                                </button>
                                <button data-bs-toggle="modal" data-bs-target="#addJobPlace" type="button"
                                    class="btn btn-success w-25 h-25">
                                    إضافة مطعوم جديد <i class="fa-solid fa-syringe fa-beat ml-3"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="successMsg" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg bg-dark">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close m-0" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <div class="modal-image">
                        <svg viewBox="1 0 30 40" style="fill: #48db71">
                            <path d="M1 14 L5 10 L13 18 L27 4 L31 8 L13 26 z"></path>
                        </svg>
                    </div>
                    <h1>تمت العملية بنجاح !</h1>
                    <p>تمت عملية تحديث بنجاح</p>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="addJobPlace" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content bg-dark bg-dark">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">إضافة مطعوم</h5>
                    <button type="button" class="btn-close m-0 bg-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="AddVaccine" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="id_name">اسم التطعيم:</label>
                                <input type="text" name="name" class="form-control" maxlength="255" required=""
                                    id="id_name">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="id_vaccine_type">نوع التطعيم:</label>
                                <select name="vaccine_type" class="form-select" required="" id="id_vaccine_type">
                                    <option value="" selected="">---------</option>
                                    <option value="BCG">تطعيم المواليد - بي سي جي</option>
                                    <option value="Polio_Newborn">تطعيم المواليد - شلل الأطفال</option>
                                    <option value="Hexavalent_2Months">تطعيم الشهرين - الطعم السداسي</option>
                                    <option value="Rotavirus_2Months">تطعيم الشهرين - طعم الروتا</option>
                                    <option value="Hexavalent_4Months">تطعيم الأربعة شهور - الطعم السداسي</option>
                                    <option value="Rotavirus_4Months">تطعيم الأربعة شهور - طعم الروتا</option>
                                    <option value="Hexavalent_6Months">تطعيم الستة شهور - الطعم السداسي</option>
                                    <option value="Rotavirus_6Months">تطعيم الستة شهور - طعم الروتا</option>
                                    <option value="Meningococcal_9Months">تطعيم التسعة شهور - تطعيمة التهاب السحايا
                                        A.C.Y.W135</option>
                                    <option value="Polio_9Months">تطعيم التسعة شهور - ال</option>
                                    <option value="Pneumococcal_1Year">تطعيم السنة - طعتطعيمة الوقاية من شلل الأطفم
                                        الرئوي
                                        13</option>
                                    <option value="Pentavalent_1.5Years">تطعيم السنة والنصف - الطعم الخماسي</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="id_available_doses">عدد الجرعات المتاحة:</label>
                                <input type="number" name="available_doses" class="form-control" required=""
                                    id="id_available_doses">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="id_expired_date">تاريخ انتهاء الصلاحية:</label>
                                <input type="date" name="expired_date" class="form-control" required=""
                                    id="id_expired_date">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="id_description">وصف التطعيم:</label>
                                <textarea name="description" class='form-control' cols="80" rows="5" required=""
                                    id="id_description"></textarea>
                            </div>
                        </div>

                    </form>
                    <div class="modal-footer">
                        <button type="submit" form="AddVaccine" class="btn btn-primary">
                            حفظ
                        </button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            أغلاق
                        </button>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="errorMsg" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg bg-dark">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close m-0" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <img src="{% static 'dist/img/error.png' %}" class="w-25 h-25 mb-3" alt="" />
                    <h1>لم تتم عملية بنجاح !</h1>
                    <p>تأكد من الاتصال او إدخال البيانات بشكل صحيح</p>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="message" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content bg-dark bg-dark">
                <div class="modal-header">
                    <h5 class="modal-title" id="">حذف جهة العمل</h5>
                    <button type="button" class="btn-close m-0 bg-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="modal-body text-center">
                        <img src="{% static 'dist/img/alert-icon.png' %}" class="w-25 h-25 mb-3" alt="" />
                        <h1>هل انت متأكد انك تريد حذف جهة العمل ؟</h1>
                        <p id="employeeNameWarrning"></p>
                    </div>
                    <form id="deleteJobPlace" method="POST">
                        {% csrf_token %}
                        <input type="number" name="id" class="d-none" value="" />
                        <div class="modal-footer">
                            <button type="button" class="btn btn-info w-25" data-bs-dismiss="modal">
                                رجوع
                            </button>
                            <button type="submit" class="btn btn-danger w-25">تأكيد</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
{% endblock scripts %}